{% set name = "pylocuszoom" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5aa46c51631e2c736867b85144f390da94f813146eeef5f943038a772820022e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - matplotlib-base >=3.5.0
    - pandas >=1.4.0
    - numpy >=1.21.0
    - loguru >=0.7.0
    - pyliftover >=0.4
    - plotly >=5.0.0
    - bokeh >=3.8.2
    - python-kaleido >=0.2.0
    - adjusttext >=0.8

test:
  imports:
    - pylocuszoom
  commands:
    - python -c "from pylocuszoom import LocusZoomPlotter"

about:
  home: https://github.com/michael-denyer/pylocuszoom
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Regional association plots for GWAS results with LD coloring
  description: |
    pyLocusZoom creates publication-quality regional association plots
    for GWAS results with LD coloring, gene tracks, and recombination
    rate overlays. Supports canine, feline, and custom species.
  dev_url: https://github.com/michael-denyer/pylocuszoom

extra:
  recipe-maintainers:
    - michael-denyer
